
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jun 18 10:38:24 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 41;
  public static final int LTE = 37;
  public static final int LOGAND = 30;
  public static final int CONST = 5;
  public static final int NUMCONST = 44;
  public static final int LPAREN = 13;
  public static final int SEMI = 7;
  public static final int CONTINUE = 19;
  public static final int MINUS = 39;
  public static final int RPAREN = 14;
  public static final int LT = 36;
  public static final int EQUALTO = 32;
  public static final int COMMA = 8;
  public static final int CLASS = 11;
  public static final int INC = 27;
  public static final int PLUS = 38;
  public static final int IF = 16;
  public static final int EOF = 0;
  public static final int RETURN = 20;
  public static final int EQUAL = 6;
  public static final int NEW = 31;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MOD = 42;
  public static final int IDENT = 47;
  public static final int BREAK = 18;
  public static final int VOID = 15;
  public static final int GTE = 35;
  public static final int TIMES = 40;
  public static final int COLON = 43;
  public static final int FOREACH = 24;
  public static final int LBRACE = 3;
  public static final int ELSE = 26;
  public static final int LSQUARE = 9;
  public static final int POINT = 23;
  public static final int READ = 21;
  public static final int CHARCONST = 45;
  public static final int RSQUARE = 10;
  public static final int WHILE = 17;
  public static final int LOGOR = 29;
  public static final int NOTEQUALTO = 33;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 46;
  public static final int EXTENDS = 12;
  public static final int DEC = 28;
  public static final int GT = 34;
  public static final int PRINT = 22;
  public static final int ARROWFUNC = 25;
}

